// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  faq: dynamic(() => import("./Faq")),
  features: dynamic(() => import("./Features")),
  gallery: dynamic(() => import("./Gallery")),
  get_app: dynamic(() => import("./GetApp")),
  hero: dynamic(() => import("./Hero")),
  how_works: dynamic(() => import("./HowWorks")),
  intro: dynamic(() => import("./Intro")),
  logos: dynamic(() => import("./Logos")),
  nav: dynamic(() => import("./Nav")),
  one_app: dynamic(() => import("./OneApp")),
  simulation: dynamic(() => import("./Simulation")),
};
